### ISSUE TITLE
Docker Run in README lacks environment PORT

### ISSUE THREAD

**Issue by ORTIC140** [PolarBookshop/polar-ui#2]
Today I checked out this repository because I needed to modify the endpoints (I am studying but making my own changes in order to try  different things). 

The Readme states.

```bash
$ docker run -d --name polar-ui --publish 9104:9004 polar-ui
```

But if you use this command the application does not run.
When I run without the -d flag gives the following error 

```bash
$ docker run  --name polar-ui --publish 9104:9004 polar-ui
023/12/06 15:43:33 [emerg] 1#0: invalid number of arguments in "listen" directive in /workspace/nginx.conf:20
```

Looking into the code it is referring to a missing port.
I then checked the configuration for the `docker-compose` and it added a PORT environment, thus I added it and now it works.

Thus, @ThomasVitale you would need to update the README.md with this fact.

**Comment by ORTIC140** [comment]
Interesting it is assigned.

Well I forgot to mention the command that works

```
$ docker run  --name polar-ui -e PORT=9004 --publish 9104:9004 polar-ui
```

**Comment by ThomasVitale** [comment]
@ORTIC140 thanks for reporting the issue. I'm currently upgrading the Angular app and the docs will be updated accordingly.

**Comment by ThomasVitale** [comment]
The documentation is now updated (see: https://github.com/PolarBookshop/polar-ui/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25). Thanks again for reporting the issue.

Soon, I'll also deliver the changes to update the application to Angular 17.
