### ISSUE TITLE
Upload Sarif V1 Deprecated

### ISSUE THREAD

**Issue by ORTIC140** [PolarBookshop/polar-ui#3]
In the GitHub Actions script

github/codeql-action/upload-sarif@v1

should be changed to use v2 as v1 is deprecated 

Error message when executing with v1 

This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

**Comment by ThomasVitale** [comment]
@ORTIC140 thanks for reporting the issue. I'm currently upgrading the Angular app and the workflow dependencies. The current ETA is the end of this week.

**Comment by ORTIC140** [comment]
Awesome! Thanks!

**Comment by ThomasVitale** [comment]
The GitHub Actions workflow is now updated (see: https://github.com/PolarBookshop/polar-ui/pull/4/files#diff-f9b113f4b860f5723113114287ad2ebec3be46fe249836920cfe464bc4d30e0fR31). Thanks again for reporting the issue.

Soon, I'll also deliver the changes to update the application to Angular 17.
